server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: vulnerableapp_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: vulnerableapp
          # RETO: Etiqueta estática de entorno
          environment: dev 
          # PASO 3: Monitoreo de múltiples archivos usando comodines
          __path__: /var/log/VulnerableApp/{log-*.txt,security-*.txt} 
          
    # PASO 4 y RETO: Enriquecimiento dinámico de registros mediante labels
    pipeline_stages:
      - regex:
          # Busca palabras clave en el texto del log
          expression: '.*(?P<keyword>Auth\.Login|Auth\.Dashboard|Search\.Index|Order\.Create).*'
      
      # Asigna la label 'category' (Application, Security, Audit)
      - template:
          source: category
          template: '{{ if eq .keyword "Auth.Login" }}Security{{ else if eq .keyword "Auth.Dashboard" }}Security{{ else if eq .keyword "Search.Index" }}Audit{{ else }}Application{{ end }}'
      
      # RETO: Asigna la label 'module' (authentication, orders, general)
      - template:
          source: module
          template: '{{ if eq .keyword "Auth.Login" }}authentication{{ else if eq .keyword "Auth.Dashboard" }}authentication{{ else if eq .keyword "Order.Create" }}orders{{ else }}general{{ end }}'
      
      - labels:
          category:
          module: